### ISSUE TITLE
create a book now page 

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/CareCompanion#10]
Hello contributors 

You have to create a book now  page for our website careCompanion.It should have  dynamic components like the reference provided below . Use react and tailwaind css .These are just references .Feel free to show your creativity.

![Screenshot 2024-12-17 154651](https://github.com/user-attachments/assets/a941ce97-3314-4383-8f4a-d45346466bf3)
![Screenshot 2024-12-17 154709](https://github.com/user-attachments/assets/213ad69b-c789-4d6c-803b-f32b0b42e865)
![Screenshot 2024-12-17 154735](https://github.com/user-attachments/assets/70b04309-41e2-44c8-be9d-73fda0256e2b)
 

Time-48 hrs

Note: comment to claim.

**Comment by Ishu0112** [comment]
I am working on it will update in 1 to 2 hours
