### ISSUE TITLE
Create Footer Component

### ISSUE THREAD

**Issue by shreeyanshi123** [opencodeiiita/CareCompanion#14]
Design Guidelines

- Add social media links and icons.
- Implement the newsletter input and submit functionality.
- Ensure responsiveness for all screen sizes.
 A design is attached for your reference feel free to customize
![navBar](https://github.com/user-attachments/assets/63ebb685-dcd0-4f9b-9811-5a2cc6d702ec)

Estimated Time:48 hours

**Comment by Butterfly222-kartiki** [comment]
claim
