### ISSUE TITLE
Building the Home Page

### ISSUE THREAD

**Issue by shreeyanshi123** [opencodeiiita/CareCompanion#18]
Create the What we Treat Section of the website. Image is attached for your reference . 

When a user hovers over the service boxes in the "What We Treat" section:
- The heading and description should dynamically appear.
- The box should highlight visually
- On clicking the "Learn More" button in any box, the user should be navigated to the respective service page.
The data to be displayed is provided in healthcare/src/Data No need for additional boxes. You are required only to create the what we treat section 

Ensure that the page is responsive .

![Screenshot 2024-12-20 150707](https://github.com/user-attachments/assets/b8ef6852-2b8e-4070-a4af-2674c6398197)
![img1](https://github.com/user-attachments/assets/be56456e-2e04-472e-b690-5facd0b318cf)

**Comment by PrinkalDhingra** [comment]
@puravimohta15 please give an update on this issue ?

**Comment by puravimohta15** [comment]
> @puravimohta15 please give an update on this issue ?

I have created a page with the required features. Should i share a preview via discord first or should i just open a PR?
