### ISSUE TITLE
Design a Navbar Component with Navigation Dropdown 

### ISSUE THREAD

**Issue by shreeyanshi123** [opencodeiiita/CareCompanion#2]
Design and implement a homepage navigation component similar to the one in the attached screenshot. The goal is to create a clean, user-friendly dropdown menu that showcases multiple sections such as What We Treat, Our Services, and Our Experts.
Implement search functionality as shown in the screenshot (top-right corner of the menu).

 Include "Book Now" and "Login" buttons in the header as separate call-to-action elements.
Make sure the Login/SignUp component are modals .
The design is attached for your reference .

Time:48hours
![navbar](https://github.com/user-attachments/assets/dad61bb4-7e27-43e1-93a5-48ecb24fb189)

Estimated hours:48

**Comment by 07CalC** [comment]
claim

**Comment by official-ashutosh** [comment]
claim

**Comment by puravimohta15** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
Hi @Butterfly222-kartiki , I noticed that the pull request was submitted after the 48-hour deadline for your task. As a result, I will be assigning it to someone else this time. Thank you for your efforts, and I appreciate your understanding!

**Comment by Butterfly222-kartiki** [comment]
@ANJALIJAISWAL4213 ok ma'am

**Comment by shreeyanshi123** [comment]
> /claim

@aashi-336 what is the update ??

**Comment by Butterfly222-kartiki** [comment]
claim
