### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by shreeyanshi123** [opencodeiiita/CareCompanion#23]
Two images are attached for your reference . The place of the components will be below the 'What we Treat Section ' of Home Page.
In the Our services section the description of the Card should be displayed when we hover over it as shown in the first picture of the Card.  
![Screenshot 2024-12-23 091454](https://github.com/user-attachments/assets/512d05e9-81c0-418a-8ee7-0d907c2c1120)
![Screenshot 2024-12-23 091501](https://github.com/user-attachments/assets/57cc4284-66b5-49d3-be8e-887415e7d0df)

Time:48hours

**Comment by Butterfly222-kartiki** [comment]
claim

**Comment by poonam17122004** [comment]
claim
