### ISSUE TITLE
Design a Responsive Carousel Component for Homepage

### ISSUE THREAD

**Issue by shreeyanshi123** [opencodeiiita/CareCompanion#3]
Design and implement a visually appealing, interactive carousel component for the homepage that highlights key content, such as promotional banners, featured services, or important messages.

Features:-
     Autoplay: Slides should advance automatically every 4-5 seconds.
    Manual Navigation: Users should be able to navigate using:
    Left and right arrow controls.
   Dot indicators or numbered pagination at the bottom to show slide progress.
   Smooth Transitions: Add smooth fade-in/out or slide animations.
    Looping: Once the last slide is shown, the carousel should loop back to the first slide.

Image is attached for your reference 
![car1](https://github.com/user-attachments/assets/c9023c70-da18-4d30-9091-50f427181d24)

Estimated Time:48 hours

**Comment by poonam17122004** [comment]
pls assign me this issue🙏🏻

**Comment by official-ashutosh** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
Hi @poonam17122004 , I noticed that the pull request was submitted after the 48-hour deadline for your task. As a result, I will be assigning it to someone else this time. Thank you for your efforts, and I appreciate your understanding!

**Comment by PrinkalDhingra** [comment]
@poonam17122004 Kindly provide an update.

**Comment by poonam17122004** [comment]
@PrinkalDhingra it's almost completed in 1/2 hour i'm gonna raise PR
